font_family	 Hermit
bold_font	 auto
italic_font	 auto
bold_italic_dont auto

font_size	 11.0
force_ltr	 no

adjust_line_height  0
adjust_column_width 0

symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols
symbol_map codepoints Font Family Name

font_features none

background_opacity 0.85

background #001e26
foreground #708183
cursor #708183
selection_background #002731
color0 #002731
color8 #001e26
color1 #d01b24
color9 #bd3612
color2 #728905
color10 #465a61
color3 #a57705
color11 #52676f
color4 #2075c7
color12 #708183
color5 #c61b6e
color13 #5856b9
color6 #259185
color14 #81908f
color7 #e9e2cb
color15 #fcf4dc
selection_foreground #001e26
